

export const allProjects = [
    {
        id: 1,
        company: "Australian Dental Association",
        year: "2019",
        title: "Congress",
        type: "website, marketing collateral, signage", 
        description: "Created pop-art themed assets for Congress, Australias leading dental conference, such as an exhibition stand, 14 exhibition features, 8 registration desk pieces, and various signs. Worked also with a developer to design the website and collaborated with other teams to meet their design needs.",
        image: "https://i.postimg.cc/CL2Q8PDn/Congress-ADA-mockup2.jpg",
        call_to_view: "assets",
        brief: "Create event signage, promotional assets and a website for a dental conference that embraces a unique and fun pop-art theme. The client wants the conference to stand out from traditional dental events, creating an atmosphere that is engaging, vibrant, and unlike any other dental conference. The pop-art theme will play a crucial role in setting the tone and enhancing the overall experience for attendees.",
        solution: "Created a vibrant pop-art hero image which served as the cornerstone for developing various assets throughout the project. Experiment with variations of the hero image, incorporating different pop-art styles and elements. This approach will helped create assets such as event signage, website and marketing collateral that showcase a variety of pop-art inspirations while staying consistent with the overall theme.",
        image_title_1: "EDM",
        image_detail1a: "https://i.postimg.cc/yYBV5kGg/email-mockup-detail-image.jpg",
        image_title_2: "Website",
        image_detail2a: "https://i.postimg.cc/RFvWB3jp/congress-website-mockup3.jpg",
        image_title_3: "Magazine Advertisement",
        image_detail3a: "https://i.postimg.cc/fRMx2Xpg/NB-mockup-detail-image1.jpg",
        image_detail3b: "https://i.postimg.cc/CLh19NMD/NB-mockup-detail-image2.jpg",
        image_title_4: "Email Banner",
        image_detail4a: "https://i.postimg.cc/PrW7vW16/congress-email-mockup.png",
        image_title_5: "Social Media",
        image_detail5a: "https://i.postimg.cc/sxwZbHt6/socialmedia-mockup-detail-image-copy.jpg",
        image_title_6: "Event Signage",
        image_detail6a: "https://i.postimg.cc/5y0B3F0F/socialmedia-mockup-detail-image1.jpg",
        image_detail6b: "https://i.postimg.cc/pT08pXZV/eventsign-mockup-detail-image2-copy.jpg",
    },
    {
        id: 2,
        company: "Association of Independent Schools NSW",
        year: "2023",
        title: "Leadership Brochure",
        type: "digital pdf", 
        description: "Designed the brochure for the 2023-2024 leadership program, aiming for a modern look. The client described their brand as people-centric, trustworthy,and future-oriented, which guided my design choices.",
        image: "https://i.postimg.cc/VN2GhDm0/leadership-brochure-mockup3.jpg",
        call_to_view: "PDF",
        call_to_view_pop_up1: "View PDF",
        viewing_link1: "https://1drv.ms/b/s!AkdltgC3-vEIg16_eLtwyW54D0le?e=RgVP2D",
        brief: "Objective of this project is to design a visually appealing and informative digital brochure promoting The AIS Leadership Centre's leadership programs that is suitable for outline distribution. The brochure should be made with the reader in mind with a logical and easy-to-follow structure and effectively communicating the value and benefits of the programs which aim to educate and empower school leaders at various career stages.",
        solution: "Developed a concise and impactful 34-page digital brochure to promote the leadership courses offered by The AIS Leadership Centre. The brochure is strategically structured, presenting the courses in a chronological order based on career stage, ensuring readers can easily identify the most relevant program for their professional development. By incorporating compelling visuals that resonate with the target audience and aligning the design with the brand's values of being people-centric, trustworthy, and future-oriented, the brochure delivers a modern and polished representation of the leadership brand.",
        image_detail1a: "https://i.postimg.cc/sgRrt5Lh/23-leadership-brochure-mockup-page1.jpg",
        image_detail2a:"https://i.postimg.cc/W3KRSZrt/23-leadership-brochure-mockup-page2.jpg",
        image_detail3a: "https://i.postimg.cc/W3JVBSs0/23-leadership-brochure-mockup-page3.jpg",
    },
    {
        id: 3,
        company: "Rough Patch",
        year: "2022",
        title: "Fundraising Animation",
        type: "animation",
        description: "An animation for Rough Patch aimed at helping rise funds to support their unique solution to the mental health crisis in Australia through various avenues. I worked closely with Rough Patch and the account manager to develop the storyboard and animation",
        image: "https://i.postimg.cc/j5mbZzkM/Rough-Patch-video-300x250.jpg",
        call_to_view: "video",
        call_to_view_pop_up1: "Watch video",
        viewing_link1: "https://www.youtube.com/watch?v=PdyoJDAELtc",
        brief: "The objective of this project is to create an engaging animation that raises awareness about Rough Patch, a social enterprise with a unique model that aims to make counselling more accessible. The animation will serve as a tool to generate awareness and support, helping Rough Patch secure funding for their initiatives. The video is to highlight how Rough Patch’s model is innovative, and how it is making counselling more accessible and affordable. It will be primarily used on social media platforms to reach a wider audience.",
        solution: "Developed a concise and informative 2-minute video introducing Rough Patch and showcasing their unique model. The video highlights different ways individuals can contribute financially, including making purchases at their shop and providing donations. Close collaboration with the account manager and subject expert from Rough Patch ensured the storyboard effectively communicated their mission. Leveraging Rough Patch's branding, the video was designed to be friendly and approachable, resonating with the target audience.",
        viewing_link1: "https://www.youtube.com/watch?v=PdyoJDAELtc",
        image_detail1a: "https://i.postimg.cc/Kc6jZnpX/rough-patch-1.gif",
        image_detail2a: "https://i.postimg.cc/6q0rNYVX/rough-patch-3.gif",
        image_detail3a: "https://i.postimg.cc/JnPFM1Rg/rough-patch-2.gif",
    },
    {
        id: 4,
        company: "Women's Justice Network",
        year: "2022",
        title: "Case of Support and Brochure",
        type: "print",
        description: "Designing a case of support and brochure for Women Justice Network, a charity focused on helping women transition out of the prison system. My goal was to create visually appealing assets that could help the organization secure funding from philanthropists and government agencies.",
        image: "https://i.postimg.cc/fyp6fDyp/WJN-portfolio-300x250-2.jpg",
        call_to_view: "assets",
        call_to_view_pop_up1: "View Case of Support",
        call_to_view_pop_up2: "View Brochure",
        viewing_link1: "https://1drv.ms/b/s!AkdltgC3-vEIg2BZSE1lsPIk5lZb?e=oa4VS7",
        viewing_link2: "https://1drv.ms/b/s!AkdltgC3-vEIg2FmRyca8az9wHzt?e=zMbsIa",
        brief: "The objective of this project is to create a compelling Case for Support and a visually appealing Brochure for Women Justice Network. These materials will serve as essential tools to secure funding from government entities or philanthropic organizations. The primary goal is to showcase the critical work of Women Justice Network and their commitment to empowering women and girls affected by or at risk of the criminal law system. The materials should emphasize the urgent need for support while conveying the importance of funding to ensure these individuals receive the necessary assistance.",
        solution: "",
        image_detail1a: "https://i.postimg.cc/hvc63rpz/WJN-caseforsupport-mockup-detail-image1.jpg",
        image_detail2a: "https://i.postimg.cc/QdTm17JR/WJN-caseforsupport-mockup-detail-image2.jpg",
        image_detail3a: "https://i.postimg.cc/SxCLJhy4/WJN-caseforsupport-mockup-detail-image3.jpg",
    },
       
    {
        id: 5,
        company: "Association of Independent Schools ",
        title: "E-newsletter Redesign",
        type: "EDM",
        description: "Redesign the ADA e-news template by conducting stakeholder interviews, researching best practices, and seeking expert advice. As a result, we increased the open-rate by an average of 20%, in addition to changing our e-news marketing strategy.",
        year: "2021",
        image: "https://i.postimg.cc/v8086Vzx/Portfolio-ADA-enewsletter2.jpg",
        call_to_view: "EDM",
        brief:"Redesign the existing monthly Electronic Direct Mail (EDM) newsletter template to be more versatile and targeted. The new template, combined with a new edm process and strategy delivers relevant content to members, promotes business offerings and ADA’s value, and enhances engagement. The template highlights different aspects of the business, such as the shop and CPD professional learning resources, and is more personalised using dynamic fields.",
        solution: "Working with internal stakeholders and the digital marketing manager, we created documentation to consult different stakeholders for each monthy EDM and and created a strategy to deliver targeted content to different member segments. Within a year, this resulted in an average increase of 20% open rates.",
        image_detail1a: "https://i.postimg.cc/XNwsLt8V/edm-mockup2.jpg",
    },
        
    
]

export const oneProject = {
    id: 1,
    company: "SheCodes",
    title: "Project One",
    description: "This is the first project",
    year: "2023",
    image: "https://via.placeholder.com/300.jpg",
    call_to_view: "pdf",
    image_detail1: "https://i.postimg.cc/CL2Q8PDn/Congress-ADA-mockup2.jpg",
}