export const allProjects = [
    {
        id: 1,
        company: "SheCodes",
        year: "2023",
        title: "Chaperone",
        role: "front-end and back-end",
        languages: "html, css, javascript, python, Django rest framework, react",
        description: "A crowdfunding website that helps charity raise funding for small, short-term projects. Worked on back-end and front-end to create relationship between projects and pledges.",
        image: "https://via.placeholder.com/300.jpg",
        title_link_1: "Deployed site",
        link_1: "https://inspiring-pudding-aa9c51.netlify.app/",
        title_link_2: "GitHub Repo Front-end",
        link_2: "https://github.com/AnnieJDesigns/chaperone-crowdfunding",
        title_link_3: "GitHub Repo Back-end",
        link_3: "https://github.com/SheCodesAus/she-codes-crowdfunding-api-project-AnnieJDesigns",
    },
    {
        id: 2,
        company: "SheCodes",
        year: "2023",
        title: "Our Profile",
        role: "front-end",
        languages: "html, css, javascript, react",
        description: "Working with the backend developers and other front-end developers, we created a website tells the success stories of women who made the career transited into technology.",
        image: "https://via.placeholder.com/300.jpg",
        title_link_1: "Deployed site",
        link_1: "https://our-people.netlify.app/",
        title_link_2: "GitHub Repo Front-end",
        link_2: "https://github.com/SheCodesAus/react-ionaries_2023_group_frontend",
    },
    {
        id: 3,
        company: "AnnieJDesigns",
        year: "2023",
        title: "Portfolio",
        role: "front-end",
        languages: "html, css, javascript, react",
        description: "A website that showcases my dev projects and my graphic design projects.",
        image: "https://via.placeholder.com/300.jpg",
        title_link_1: "GitHub Repo Front-end",
        link_1: "https://github.com/AnnieJDesigns/AnnieJPortfolio_v2"
    },
    {
        id: 4,
        company: "SheCodes",
        year: "2022",
        title: "Weather App",
        role: "",
        languages: "python, unit testing",
        description: "A Data Processing program to process and convert csv files into meaningful text-based summaries. These outputs also needed to pass pre-created Unit Tests.rowdfunding website that helps charity raise funding for small, short-term projects. Worked on back-end and front-end to create relationship between projects and pledges.",
        image: "https://via.placeholder.com/300.jpg",
        title_link_2: "GitHub Repo",
        link_2: "https://github.com/AnnieJDesigns/chaperone-crowdfunding",
    },
]

export const oneProject = {
    id: 1,
    company: "SheCodes",
    year: "2023",
    title: "Chaperone",
    role: "front-end and back-end",
    languages: "html, css, javascript, python, Django rest framework, react",
    description: "A crowdfunding website that helps charity raise funding for small, short-term projects. Worked on back-end and front-end to create relationship between projects and pledges.",
    image: "https://via.placeholder.com/300.jpg",
    title_link_1: "Deployed site",
    link_1: "https://inspiring-pudding-aa9c51.netlify.app/",
    title_link_2: "GitHub Repo Front-end",
    link_2: "https://github.com/AnnieJDesigns/chaperone-crowdfunding",
    title_link_3: "GitHub Repo Back-end",
    link_3: "https://github.com/SheCodesAus/she-codes-crowdfunding-api-project-AnnieJDesigns",
}